# Generated by Django 5.1.7 on 2025-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
